### ISSUE TITLE
Implement "withoutTags" feature to notification-banner/overlay

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#1110]
Scope
---
In SSR projects we have to include the overlay/banner via dangerouslySetInnerHTML. At the moment it has to be wrapped in a `div`. With the noTags option like e.g. in the partials `coreStyles()` we could use a `<script>` tag.

<img width="888" alt="Bildschirmfoto 2021-01-11 um 16 30 45" src="https://user-images.githubusercontent.com/60395476/104202127-cecf8c00-542a-11eb-8d1e-797b877c973c.png">

Out of Scope
---
List topics that are not part of this task.

Notes  
---
- Think of using JSX as alternative output?

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by denyo** [comment]
`withoutTags` was deprecated and will be removed in v3. Therefore this ticket is obsolete. 
A better solution for JSX would be to offer something like
```
// exporting it like this
export function PDSInitialStyles(props) {
  return getInitialStyles({ format: "jsx", ...props });
}
// or this, will make it more React like
export { getInitialStyles as PDSInitialStyles };
```
