### ISSUE TITLE
Extend PorscheDesignSystem{Provider|Module} to set default props on components, eg. dark theme

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#1185]
Scope
---
Since we are now in control of `PorscheDesignSystemProvider` in `components-{react|vue}` and `PorscheDesignSystemModule` in `components-angular` we are able to provide useful default configurations for our components that would otherwise be very repetitive. For example we could offer the ability to set the `theme` of all components within the `Provider|Module` to `dark|light|auto`.

Notes  
---
- Local component prop definition always has priority over a default configuration on Provider/Module level
- Ensure it's working in SSR context (NextJS/Remix) too
- What happens, when multiple Provider/Modules are getting initialised with different configurations?
- Provide a scalable solution to add more default props later on. Example how 
MaterialUI does it: https://mui.com/material-ui/customization/theme-components/
- Only possible for Frameworks (not for VanillaJS)

Acceptance criteria
---
- [x] A default theme (`dark|light|auto`) can be set on `Provider|Module` level for `components-{react|vue|angular}` which is getting reflected by all child components

Subtasks
---
- [x] Angular
- [x] React
- [x] React SSR
- [x] UXPin
- [x] Vue
- [x] Tests
- [x] Documentation
- [x] Changelog

**Comment by breathingearth** [comment]
Is there any update when the change will come?
For me it is mandatory to introduce a switch for night mode.

**Comment by stephanschroeter** [comment]
We'll refine and priorize this issue with our next regular refinement ritual.
