### ISSUE TITLE
Autogenerated Props of Headline are incomplete

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#1295]
Scope
---
There is an edge-case while generating the headline props where the standard headline variants (`headline-1/2/3`) are missing.

<img width="900" alt="Bildschirmfoto 2021-03-30 um 09 38 19" src="https://user-images.githubusercontent.com/60395476/112951469-ac9cfe80-913b-11eb-983b-d34706dbede8.png">

Also props should be sorted, at the moment they are random:
<img width="473" alt="Bildschirmfoto 2021-04-28 um 13 41 21" src="https://user-images.githubusercontent.com/60395476/116398175-cb201380-a827-11eb-96f0-04c28ba8d4b6.png">

Events are not displayed correctly, could be improved.

Acceptance criteria
---
- [ ] All viable props are displayed
- [ ] Sorted props to avoid fixture changes in vrt tests
- [ ] Events are displayed correctly

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
Component is deprecated anyway
