### ISSUE TITLE
Skeleton Follow Up

### ISSUE THREAD

**Issue by SetupCoding** [porsche-design-system/porsche-design-system#1776]
Scope
---
Follow up ticket for: https://github.com/porscheui/porsche-design-system/issues/1339

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] remove `var(--p-override-skeleton-animation-duration, 1.5s)` from production skeleton styles
- [ ] check styles + flash of skeleton of slotted button in p-text 
- [ ] Provide a skeleton loading in utility package for a custom solution
- [ ] headline variant as `headline-1` but also `x-large` is possible, adjust skeleton property selectors?
- [ ] discuss "non initial" skeleton styles
- [ ] handle breakpoint customizable on skeleton property classes
- [ ] remove skeleton styles after the design system is loaded (Vanilla JS)
- [ ] remove skeleton classes on react and angular components wrapper by adjusting stencil core
- [ ] add a PR to the slfinpub-finder with our new skeletons
- [ ] remove unused selectors when `skeletonTagNames` are provided for one of the composed keys like `p-select-wrapper|p-text-field-wrapper`
- add skeletons for missing components:
- [ ] extend stencil component decorator to hold data like hasSkeleton and usesSlot
- [ ] Accordion
- [ ] Marque?
- [ ] Pagination
- [ ] Popover?
- [ ] Switch
- [ ] Table?
- [ ] Tabs
- [ ] Tabs Bar

Ideas
---
- [ ] aria? 
- [ ] possible patch (postinstall) of hydrated stencil styles -> warning of patched initial styles to use partial
- [ ] possibly remove dead code of stencil-core, which was adding css to shadowroot  https://github.com/ionic-team/stencil/blob/16b8ea4dabb22024872a38bc58ba1dcf1c7cc25b/src/runtime/styles.ts 

Components (in frameworks) that need classes set based on properties
---
Component | Property | Default
-- | -- | --
Accordion | `compact`<br>`open`<br>`size (text)`<br> | `false`<br>`false`<br>`'small'`
Marque | `size` | `'responsive'`
Popover |   |  
Switch | `hideLabel`<br>`stretch` | `false`<br>`false`
Text field | `description`<br>`hideLabel` | `''`<br>  `false`
Textarea | `description`<br>  `hideLabel` | `''`<br>  `false`

**Comment by stephanschroeter** [comment]
won't implement
