### ISSUE TITLE
Replace JSS Core

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#1800]
Scope
---
Currently we bundle the JSS Core into our main/core chunk.

Since we don't use a big part of it and it's flexibility for all kinds of style nesting, rule referencing, extending, etc. we should replace it with something custom.

The idea is to simply transform the `Styles` object into a string just like JSS does while removing duplicate media queries since `jssPluginSortMediaQueries` plugin doesn't work properly with `@global`.

Since all of our styles are tested via snapshots this refactoring should be doable with high confidence.

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
JSS Core is just fine for our use case.
