### ISSUE TITLE
Verify npm login registry url in the documentation

### ISSUE THREAD

**Issue by SetupCoding** [porsche-design-system/porsche-design-system#1801]
Scope
---
Reported by:
https://porschedev.slack.com/archives/CT7AVHTTQ/p1646924341832699
It is possible that the  registry url in the documentation is wrong:
https://designsystem.porsche.com/v2/start-coding/introduction
URL provided in docs: https://porscheui.jfrog.io/porscheui/api/npm/npm/ -> gave 401 on login
URL used by user: https://porschedev.jfrog.io/porschedev/api/npm/public-npm/ -> worked

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by denyo** [comment]
We no longer publish to jfrog.
