### ISSUE TITLE
Move fonts, marque, email, icons, meta-icons into assets as sub project

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#1848]
Scope
---
Describe clearly the scope of the task.

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by denyo** [comment]
Duplicate of #2709
