### ISSUE TITLE
Add documentation to new utilities sub package

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#1866]
Scope
---
Our `@porsche-design-system/components-{js|angular|react}` package provides a `utilities` sub-package which was released silently.
The `@porsche-design-system/utilities` will be marked deprecated (#1867) and the new sub-package should be used.

We need to provide updated documentation on how to use the sub-package and what is provided in it. Therefor it will be necessary to provide UtilitiesDocs component which might use the Playground Vue component internally reflecting `scss`, `jss` and `styled-component` integration examples.
Also the documentation of the deprecated `@porsche-design-system/utilities` should be removed.

Notes  
---
- Documentation of deprecated package https://designsystem.porsche.com/v2/utilities/introduction
- If possible generate `scss`, `styled-components`, `jss` examples based on js variant of utilities sub-package

Acceptance criteria
---
- [x] Documentation on how to use the `utilities` sub-package of `@porsche-design-system/components-{js|angular|react}` is provided
- [x] Code examples for `scss`, `jss` and `styled-component` integration examples (like done with Angular, React and JS component examples and partial docs) are provided
- [x] `Flex`, `Grid`, `Content Wrapper` are deprecated with a short `Inline Notification` in Storefront docs

Subtasks
---
- [ ] Task

**Comment by marcelbertram** [comment]
Wont be fixed due to new styles package
