### ISSUE TITLE
Active state color for Tabs Bar in theme dark on background color surface has not enough contrast

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#2019]
Description  
---
The contrast ratio of active state color for `Tabs` + `Tabs Bar` in theme dark on background color surface is too low.

**Important:** In our `accessibility.a11y.ts`, the `a11yAnalyze()` test is currently disabled to enable pipeline runs. This has to be enabled again when fixed!

Out of scope
---
- Find a solution that only affects `Tabs` + `Tabs Bar` component
- Don't fix any other component
- Don't extend tests to cover possible issues with other components

To Reproduce
---
1. Go to https://designsystem.porsche.com/v2/components/tabs/examples#gradient-color-scheme
2. Click on `Dark Theme`
3. Check contrast ratio of active tab color
4. Contrast ratio is 3.6

Expected behavior
---
Contrast ratio has to be at least 4.5

Notes
---
- Make the active tab element use themed base text color instead of themed active color
- Make sure to update Sketch Library

Screenshots
---
![Bildschirmfoto 2022-08-24 um 11 38 57](https://user-images.githubusercontent.com/60395476/186385717-96a76c5d-7cae-4270-9131-38c3183f6320.png)

Test Environment
---
Platform/Browser/Version: [e.g. iOS Safari 11, macOS Chrome 81]

**Comment by o-hook** [comment]
Won't be fixed in `v2` but in `v3` of PDS components
