### ISSUE TITLE
Missing change detection for tabindex in button, button-pure and switch

### ISSUE THREAD

**Issue by tatjana-gartner2** [porsche-design-system/porsche-design-system#2024]
Description 
---

1) Change detection for tabindex in button, button-pure and switch is missing.
2) Property "tabbable" is deprecated since v2.8.0, we should support deprecated and updated solution (`tabindex="-1"`)

To Reproduce
---
1. Go to 'button/button-pure/switch'
2. Change tabindex after component was rendered
4. Change won't be detected

Expected behavior
---
1. Go to 'button/button-pure/switch'
2. Change tabindex after component was rendered
4. Tabindex is updated

Notes
---
How to solve issue:
1. Prioritize tabindex of host over tabbable prop within render function
2. Integrate host attribute observer or observe `tabIndex` property on host and force a re-render in case `tabindex` attribute or `tabIndex` property has changed

**Comment by stephanschroeter** [comment]
fixed with v3
