### ISSUE TITLE
Spike: Set font-weight to bold for active state

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2057]
Scope
---
To have a better visual differentiation of the (currently red) active state, we want to spike the possibility to set the font-weight of the text from regular to bold without breaking the component width.

Notes  
---
- CSS trick using pseudo elements: https://darn.es/building-tabs-in-web-components/#adjusting-for-tab-weight-changes
- Components with active state: Link/Button-Pure, Tabs, Segmented Control, Select option, Pagination

Acceptance Criteria
---
- [ ] Possibility of adjusting the font-weight of text from regular to bold for active states is evaluated

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
solved differently in v3
