### ISSUE TITLE
Provide test automation for :hover media queries

### ISSUE THREAD

**Issue by SetupCoding** [porsche-design-system/porsche-design-system#2073]
Scope
---
Check if test automation for :hover media queries is possible with playwright (e.g. in the (hover/focus/hover+focus sates tests)
If not, hover media query should be replaced by a JS workaround (e.g. dynamically adding styles, based on variable)

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
Duplicate #2501
