### ISSUE TITLE
Use new <dialog> component / inert attribute

### ISSUE THREAD

**Issue by SetupCoding** [porsche-design-system/porsche-design-system#2076]
Scope
---

Our current Modal has workarounds in place to support the correct focus behaviour.
Alternatively we could implement the `intert` attribute or `dialog` Element to provide future proof features.

Article https://web.dev/building-a-dialog-component/

https://caniuse.com/?search=inert
https://caniuse.com/?search=dialog

Out of Scope
---
List topics that are not part of this task.

Notes  
---
- Related: #2285

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by o-hook** [comment]
duplicate of #2682
