### ISSUE TITLE
Split/Remove/Rename Components (e.g. Link Pure Subline / Conditional Components)

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2160]
Scope
---
Describe clearly the scope of the task.

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
Link Pure with subline does not exist in v3 anymore.
