### ISSUE TITLE
Improve SSR support for active state of Tabs / Tabs-Bar

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2176]
Scope
---
Currently it's not possible to render the active state of Tabs / Tabs-Bar in SSR context since it relies on DOM manipulation outside of the `render()` function. We should try to improve at least the visual indicator of which Tab is active within SSR context.

Notes  
---
- A CSS only solution for coloring the active Tab is to prefer
- Underline of active Tab might not be possible to visualize within SSR context

Acceptance criteria
---
- [ ] Active state of Tabs / Tabs-Bar is visualized within SSR context

Subtasks
---
- [ ] Task

**Comment by marcelbertram** [comment]
will be done with #2611
