### ISSUE TITLE
[BUG] - Code example in storefront are wrong

### ISSUE THREAD

**Issue by mhaegeleMHP** [porsche-design-system/porsche-design-system#2240]
### Contact Details

Feedback to Immo Stanke in our slack tool channel

### JS Framework

Storefront

### Porsche Design System version

2.19.0

### Reproduction Example

https://designsystem.porsche.com/v2/components/modal/examples#without-close-button

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/v2/components/modal/examples#without-close-button
2. Click on Framework `Angular` / `React`
3. `disable-close-button` property is displayed wrong

### Expected behavior

`disable-close-button` should be `disableCloseButton`

### Relevant log output

![Bildschirmfoto 2023-01-12 um 14 23 17](https://user-images.githubusercontent.com/60395476/212078051-33e99344-bbbf-42ed-8c40-ab132c3e587f.png)

![Bildschirmfoto 2023-01-12 um 14 23 33](https://user-images.githubusercontent.com/60395476/212078148-beabbd37-0bc6-4295-9ddf-3018d06bcf4f.png)

**Comment by denyo** [comment]
Fixed as part of #2229
