### ISSUE TITLE
[BUG] - p-tag slotted styles can be overwritten by inherited styles (font-size)

### ISSUE THREAD

**Issue by tatjana-mariella** [porsche-design-system/porsche-design-system#2243]
### JS Framework

all frameworks

### Porsche Design System version

2.19.0

### What browsers are you seeing the problem on?

Firefox, Mobile Firefox, Chrome, Mobile Chrome, Safari, Mobile Safari, Microsoft Edge

### Reproduction Example

/

### Steps to reproduce the behavior

Run p-tag with e.g. <b></b> tag in the slot and change the font size of the parent element.

### Expected behavior

The slotted elements are not affected by changing the font-size on the parent element (similar to p-text).

**Comment by stephanschroeter** [comment]
Not reproducible anymore.
