### ISSUE TITLE
[BUG] - Marque of PHN Header is infront of P-Banner component

### ISSUE THREAD

**Issue by anotherMatze** [porsche-design-system/porsche-design-system#2262]
### Contact Details

Alexander Schnebel, Slack

### JS Framework

React

### Porsche Design System version

2.19.0

### What browsers are you seeing the problem on?

Chrome

### Reproduction Example

Reproducible in sample integration

### Steps to reproduce the behavior

- Checkout https://github.com/porsche-design-system/sample-integration-react
- Add Banner to PHN-Header page
- See error

![image (4)](https://user-images.githubusercontent.com/60395476/214260540-9363622b-7465-4cd7-95f0-17611850ec69.png)

### Expected behavior

Banner should be in front.

**Comment by marcelbertram** [comment]
https://react.preview-nav.porsche.com/?NAVI_3=true&navi_3=true

**Comment by denyo** [comment]
<img width="711" alt="Bildschirmfoto 2023-04-20 um 14 41 54" src="https://user-images.githubusercontent.com/4380295/233369320-d245ffe5-8d1b-47e0-8744-0f76a536e65f.png">

**Comment by stephanschroeter** [comment]
Issue doen't exist anymore.
