### ISSUE TITLE
[BLOCKED] V3 Status To Do's

### ISSUE THREAD

**Issue by tatjana-mariella** [porsche-design-system/porsche-design-system#2321]
Scope
---
- custom slotted styles shall be transferred to normalize styles (getInitialStyles partial)
- default browser input icons don't respect color definition in dark theme
- Safari/Chrome browser hasn't correct height and color (dark theme) when type date or time is used

Acceptance criteria
---

Subtasks
---
- [x] Transfer slotted styles to initialStyles partial
- [x] fix initial styles partial (it was still using v2 tokens and styles)
- [x] fix default icon color on dark theme -> tbd: Use p-button pure / icon -> therefore browserspecific solutions would be necessary
- [x] fix input type date / time height in safari
- [x] fix input type date / time text color in safari
- [x] Code Block is selectable and focusable again
- [x] Refactored standard initial styles
- [x] Add slotted anchor support for dedicated components
- [x] Get rid of `getSlottedCss` entierly
- [x] Update VRT tests for slotted anchor (light|dark)
- [x] Update VRT tests for slotted anchor (hover|focus)
- [x] Use one VRT page for modal
- [x] ~~Use one VRT page for toast~~
- [x] Add auto-layout to vrt playground
- [x] remove getDataThemeDarkAttribute() from components
- [x] Add multi prefix support for initial styles
- [ ] Add vrt test for initial styles
- [ ] Add vrt test for initial styles (multi prefix)
- [ ] Fix selectable support for components when focused
- [ ] re-use `getHoverStyle()` and `getFocusStyle()`
- [ ] focus causes text shift on e.g. banner
- [ ] `calc(6px + 2.125ex)` needs to be set by `*` selector?
- [ ] add date/time vrt states test for text-field
- [ ] ensure hover/focus style is working the same for scss
- [ ] move modal scrollable vrt test away from end of the page
- [ ] shall switch support nested anchor for label?
- [ ] enable react modal vrt test, as soon as prefix for initial styles is supported
- [ ] ssr support for text-field could be improved
- [ ] enable modal vrt test for angular
- [ ] add getInitialStyles unit test (unminified, by mocking getMinifiedCss())
- [ ] update focus migration path (no theme needed anymore)
- [ ] improve import `import { addImportantToEachRule } from '@porsche-design-system/components/src/styles';`
- [ ] fix `initialStylesWithoutMediaQuery` in `puppeteer-helper.ts`
- [ ] add unit test for `_hasShowPickerSupport()`
- [ ] hover for e.g. p-link-pure does not work at all
- [x] adjust border radius large to 12px
---
'p-accordion', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-banner', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-carousel', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-checkbox-wrapper', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-display', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-heading', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-headline', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-inline-notification', // VRT - light: ✅ dark: ✅ hover/focus: 🚧 docs: 🚧
'p-modal', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-popover', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-radio-button-wrapper', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-select-wrapper', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-switch', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-table', // VRT - light: 🚧 dark: 🚧 hover/focus: 🚧 docs: 🚧
'p-tabs', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-text', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-text-field-wrapper', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-text-list', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧
'p-textarea-wrapper', // VRT - light: ✅ dark: ✅ hover/focus: ✅ docs: 🚧

**Comment by stephanschroeter** [comment]
Multiline focus does not work:
![Image](https://user-images.githubusercontent.com/30120450/222676015-6f2cea1c-981d-42b0-bbde-9ddd0b54283a.png)

**Comment by stephanschroeter** [comment]
When getting focused, text gets wrapped into new line:
![Image](https://user-images.githubusercontent.com/30120450/222679182-635abb5d-5ef0-42bb-b7e3-5504869abb3b.png)

**Comment by stephanschroeter** [comment]
Is it correct for Segmented Control?
![Image](https://user-images.githubusercontent.com/30120450/223131201-6648d513-73c2-4241-b95e-1af0beb24bba.png)

**Comment by stephanschroeter** [comment]
Ensure slotted elements get colored by theme-{light|dark}-primary
![Image](https://user-images.githubusercontent.com/30120450/223750422-73f31424-91e0-4591-8186-88d05588e22f.png)

**Comment by stephanschroeter** [comment]
https://user-images.githubusercontent.com/30120450/224061451-3a9cabf9-c684-4cee-bab5-9357f681ff69.mov
