### ISSUE TITLE
Create Component / Model Link Tile

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2353]
Scope
---
To support a consistent appearance for specific link tiles that are used for model series we want to provide a model tile component, e.g. used in finder home and check in 

Specs
---
- Name `model-tile` | `model-link-tile` | `link-tile-model` | `…`
- Only link variant (no button variant needed)
- No compact
- No align prop
- ~Aspect ratio only 4:3, 3:4, 9:16~ Same as Link tile
- define 2 links: primary (complete tile + primary link) and secondary (secondary link)
- model-signature top left

Out of Scope
---
- No image handling

Notes  
---
- Figma: https://www.figma.com/file/EkdP468u4ZVuIRwalKCscb/Design-System-v3?node-id=8140%3A57961&t=J2fZ155wV15Dzg1a-0
- Don't use `link tile` internally
- ~Ensure JS framework routing is working without slotted anchor~ (works at the moment like link tile, framework routing is outscoped in seperate ticket)

Acceptance criteria
---
- [x] Model Link Tile component is available and documented

Subtasks
---
- [x] Create Component
- [x] share styles with link tile
- [x] validate slots
- [x] refactor weight semiBold to semi-bold
- [x] create alias for types with component prefix
- [x] find a generic way to set requird props in unit test and e2e
- [x] check for custom slotted styles in initalStyles partial (picture > img)
- [x] clean index.html
- [x] clean assets
- [x] add prop validation
- [x] Add unit tests
- [x] check chunk size of link tile
- [x] think about signature size, should it change? If how?
- [x] Add e2e tests
- [x] add focus behavior test
- [x] add lifecycle tests
- [x] add vrt tests, component + overview
- [x] add scaling / high contrast vrt test
- [x] add storefront docu
- [x] ssr check
- [x] think about directions naming
- [x] Talk about JSSDirections naming
- [x] cross browser check
- [x] uxpin check
- [x] changelog entry
- [x] check hover state vrt
- [x] check where the picture is
- [x] 320px width not correct
- [x] unit test direction jss
- [x] unit test link button tile styles
- [x] change default aspect ratio to 3:4
- [x] remove top gradient
- [x] support `p-link` with slotted a
- [x] solve framework routing
- [x] uxpin check

Questions
---
- ~No slotted anchor support?~
- what about size? -> predefined size, no prop
- what about weight? -> semibold + regular
- what about "sub-description"? -> size + weight not customizable
- ~how to pass label + href for primary / secondary links?~ -> p-link in slot
- ~link group grid, mediaquery or width of element?~
- whats our default weight? -> sync to link-tile

**Comment by leifmarcus** [comment]
How does this component behave, when the element is not instantiated yet? Is the image inside giving the correct size, so that there will be no layout shift during initialization? That would be really important for us.
