### ISSUE TITLE
[BUG] - Non-Breaking Hyphens are not rendered correctly

### ISSUE THREAD

**Issue by leifmarcus** [porsche-design-system/porsche-design-system#2438]
### Contact Details

@leifmarcus 

### JS Framework

Not related to the framework

### Porsche Design System version

3.0.0-alpha.3

### What browsers are you seeing the problem on?

Chrome

### Browser version

110.0.5481.177

### Reproduction Example

https://stackblitz.com/edit/liqqv8-fw3pzy?file=index.html

### Steps to reproduce the behavior

1. Add a `p-heading` (or any other typography element) to the page.
2. Add a text with non-breaking-hyphen inside the tags like `<p-heading>E&#8209;Performance</p-heading>`
3. Open the page with the chrome browser
4. See the wrong character for the non-breaking hyphen.

### Expected behavior

The non-breaking hyphen should render correctly. If you need an example, you should open the same page in Safari or Firefox, where this error is not the case.

### Wrong Rendering (screenshot in Chrome)
<img width="275" alt="image" src="https://user-images.githubusercontent.com/2342671/228640994-c0f53964-b424-4abb-817c-e8fa3b5851a6.png">

### Correct Rendering (screenshot in Safari)
<img width="271" alt="image" src="https://user-images.githubusercontent.com/2342671/228641210-a854cb3a-9de3-49a4-a74a-47851e808bbd.png">

### Relevant log output

```shell
Loaded unicode ranges in chrome inspected via document.fonts:

U+20-7F, U+80-FF, U+100-17F, U+180-24F, U+250-2AF, U+2B0-2FF, U+300-36F, U+E00-E7F, U+1E00-1EFF, U+2000-206F, U+2070-209F, U+20A0-20CF, U+2100-214F, U+2150-218F, U+2190-21FF, U+2200-22FF, U+25A0-25FF, U+2600-26FF, U+FB00-FB4F, U+FE70-FEFF U+20-7F, U+80-FF, U+100-17F, U+180-24F, U+250-2AF, U+2B0-2FF, U+300-36F, U+E00-E7F, U+1E00-1EFF, U+2000-206F, U+2070-209F, U+20A0-20CF, U+2100-214F, U+2150-218F, U+2190-21FF, U+2200-22FF, U+25A0-25FF, U+2600-26FF, U+FB00-FB4F, U+FE70-FEFF

The non-breaking hyphen is part of U+2000-206F which is included.
```

**Comment by marcelbertram** [comment]
seems to be fixed
