### ISSUE TITLE
Provide code example for vehicle image with model signature background

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2469]
Scope
---
To create the desired design, teams need to place a model signature behind an according image of the vehicle. See the example below. Since teams are having trouble with a consistent implementation a best practice code example would help teams to build a consistent appearance. 

Out of Scope
---
- Do not change the model signature component

Notes  
---
- Focus on 2 model: 911 and Cayenne
- Consider responsive behavior
- Use Signature Component
- Use model assets attached
- A developer requested to get rid of the reserved whitespace underneath the signatures that have no descendent. We want to keep the whitespace to have the same visual balance when setting an identical height for all signatures.

Talk to designers for further details!
https://www.figma.com/file/0GbGhymVN01gdkpWBTv8wS/Overview-%26-Key-Screens?node-id=16200%3A157779&t=qWGoZfsbv7CQBNSJ-1

Acceptance criteria
---
- [ ] Provide a new section in patterns model signature sideshot with code example with overlap for all signatures & model
- [ ] Basic usage guidance to new "model signature sideshot pattern" section is provided
- [ ] "Model signature sideshot pattern" section is mentioned and linked in model signature component

Subtasks
---

<img width="1123" alt="Bildschirm­foto 2023-04-13 um 17 44 03" src="https://user-images.githubusercontent.com/42403731/231813443-15b7b48d-8f4b-4dc0-9869-755873254449.png">

**Comment by neuncreative** [comment]
![911](https://user-images.githubusercontent.com/42403731/231816569-9cf42717-a2b0-40e6-9e25-471a18a76d26.png)
![cayenne](https://user-images.githubusercontent.com/42403731/231816595-e1fb6df0-9809-4f51-bb30-741fe63a708e.png)
