### ISSUE TITLE
[BUG] - Text in popover overlay can not be marked

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2492]
### JS Framework

all

### Porsche Design System version

3.0

### Reproduction Example

https://designsystem.porsche.com/v3/components/popover/examples

### Steps to reproduce the behavior

4. See error'

### Expected behavior

Text in popover overlay can be marked, e.g. to copy

**Comment by tatjana-gartner2** [comment]
Seems to be broken, since #1221 is merged (https://designsystem.porsche.com/issue/1221/components/popover/examples). 
<img width="1109" alt="image" src="https://github.com/porsche-design-system/porsche-design-system/assets/109523972/dd7ca683-df01-448f-aa60-3b37a0aded25">
