### ISSUE TITLE
[BUG] - Content of Tab Item is not selectable

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2571]
### Contact Details

samuel.schneider.extern@porsche.digital (Car Sales)

### JS Framework

NextJS

### Porsche Design System version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Reproduction Example

-

### Notes
- Maybe it's fixable with `pointer-events: none` or by using our new focus style

### Steps to reproduce the behavior

1. Go to [https://designsystem.porsche.com/v3/components/tabs/examples#basic-example](https://designsystem.porsche.com/v3/components/tabs/examples#basic-example)
2. See error, content of Tab Item is not selectable

### Expected behavior

Content of Tab Item shall be selectable

**Comment by kevelopment** [comment]
Can confirm this behaviour in Firefox as well
