### ISSUE TITLE
[BUG] - Select is not shown properly in Chrome

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2573]
### Contact Details

Luis G. (My Porsche)
Patricia H. (Car Sales)

### JS Framework

Angular, React (NextJS)

### Porsche Design System version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

v113 on Windows
Chrome on Android
Chrome on Mac or Windows

### Reproduction Example

https://my.porsche-preview.com/content/de/de_DE/events/5NVUrve5zDMRVh55LXhzPr

### Steps to reproduce the behavior

1. Go to [https://my.porsche-preview.com/content/de/de_DE/events/5NVUrve5zDMRVh55LXhzPr](https://my.porsche-preview.com/content/de/de_DE/events/5NVUrve5zDMRVh55LXhzPr)
2. See error, Select does not show border

![image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/18538919-43e0-4bd5-b9b4-06787de0440b)

### Expected behavior

Select must always show a border.

**Comment by marcelbertram** [comment]
https://github.com/porsche-design-system/porsche-design-system/assets/42934679/27d0ef79-44fd-489e-8a95-c76e594a753d
https://github.com/porsche-design-system/porsche-design-system/assets/42934679/f5c0c069-ff80-4f74-8749-d10ff31876a9

**Comment by marcelbertram** [comment]
https://github.com/porsche-design-system/porsche-design-system/assets/42934679/94b9d6bc-0ca1-4584-8aab-519e9402d569

**Comment by marcelbertram** [comment]
https://github.com/porsche-design-system/porsche-design-system/assets/42934679/664d21b3-d1a9-4695-aef5-0c53e151fd38
