### ISSUE TITLE
[BUG] - Text is not centred in Segmented Control / Causing unintended line-breaks

### ISSUE THREAD

**Issue by tatjana-gartner2** [porsche-design-system/porsche-design-system#2576]
### JS Framework

angular

### Porsche Design System version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Notes
---
- Currently the width is calculated with default font and not porsche next?

### Reproduction Example

https://stackblitz.com/edit/angular-utlvaw?devToolsHeight=33&file=src%2Fmain.ts

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/angular-utlvaw?devToolsHeight=33&file=src%2Fmain.ts
2. See error'

or

1. Go to https://designsystem.porsche.com/v3/components/segmented-control/examples
2. See "Option 1" line-break

slack report: https://porschedev.slack.com/archives/CT7AVHTTQ/p1684842995794039
And: https://porschedev.slack.com/archives/CT7AVHTTQ/p1685953736751829

### Expected behavior

- Text should be centred horizontally within segmented control.
- No unintended Line-break, e.g. in Storefront example with "Option 1"

**Comment by DelgadoRemiz** [comment]
Hi PDS team,
are there any plans to work on this bug in next time?
