### ISSUE TITLE
[BUG] - Navigation between 2 pages is not working as expected with Stepper Horizontal states

### ISSUE THREAD

**Issue by tatjana-gartner2** [porsche-design-system/porsche-design-system#2577]
### JS Framework

angular

### Porsche Design System version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Reproduction Example

https://porschedev.slack.com/archives/CT7AVHTTQ/p1684917028128699?thread_ts=1684840923.554569&cid=CT7AVHTTQ

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/angular-7arksq?devToolsHeight=33&file=src%2Fstart.component.ts
2. Click on 'to second page'
3. See error

### Expected behavior

No error for the intended outcome - either by modification of the component or different implementation (docs, validation, feedback in channel)

### Relevant log output

```shell
zone.js:141 Uncaught TypeError: Cannot read properties of undefined (reading 'shadowRoot')
    at porsche-design-system.stepper-horizontal.eb1d0a47b8f56bcb98f7.js:1:11248
    at u (porsche-design-system.stepper-horizontal.eb1d0a47b8f56bcb98f7.js:1:11288)
    at z.scrollIntoView (porsche-design-system.stepper-horizontal.eb1d0a47b8f56bcb98f7.js:1:3874)
    at porsche-design-system.stepper-horizontal.eb1d0a47b8f56bcb98f7.js:1:4420
    at porsche-design-system.v3.0.0.7acdc00ea94aef5759a7.js:1:43221
    at Array.forEach (<anonymous>)
    at MutationObserver.sn (porsche-design-system.v3.0.0.7acdc00ea94aef5759a7.js:1:43200)
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Zone.runGuarded (zone.js:137:47)
    at MutationObserver.<anonymous> (zone.js:121:29)
```

### Notes
- Different implementation without an error: https://stackblitz.com/edit/angular-z5tovf?devToolsHeight=33&file=src%2Fstart.component.ts,src%2Futils.ts,src%2Fapp.component.ts

**Comment by DelgadoRemiz** [comment]
Hi PDS team,
are there any plans to work on this bug in next time?
