### ISSUE TITLE
Apply styles direcltly in props sidepanel (like Figma)

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2617]
Scope
---
To apply typography and fill styles to components users have to switch to classic design system library and search for appropriate setting to apply instead of directly override in the props panel.

Notes  
---
- It would be the best usability to directly integrate it into the props panel for canvas
- See Figma: 
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/42934679/5b5fd27a-0f26-4480-a3ea-acc2f2c7d2b9)

Acceptance criteria
---
- [ ] Styles can be directly applied from the props panel

**Comment by Mayaleeeee** [comment]
I would love to work on this issue. @marcelbertram

**Comment by marcelbertram** [comment]
@Mayaleeeee you have to get in contact with UX Pin because this is related to their tool.
