### ISSUE TITLE
Enable background blur style

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2618]
Scope
---
In the Design System we have a background blur definition for surfaces. Thats why we need to represent this in UX Pin for Fills as well. Currently blur styles are applied to the layer but not the background.

Out of scope
---
- only background blur relevant at the moment

Notes  
---
- See Figma: 
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/42934679/a16a9b46-7f0b-43c8-a9b5-2738294c39b4)

Acceptance criteria
---
- [ ] Enable to apply blur to backgrounds

**Comment by Mayaleeeee** [comment]
Hello @marcelbertram 
Is this issue available?

**Comment by marcelbertram** [comment]
@Mayaleeeee you have to get in contact with UX Pin because this is related to their tool.

**Comment by Mayaleeeee** [comment]
> @Mayaleeeee you have to get in contact with UX Pin because this is related to their tool.

Oh, thank you @marcelbertram 
How do I go about that please?

I also wanted to contribute to Porsche as a UX Researcher and Designer, but I couldn't see any link leading to the slack community.
