### ISSUE TITLE
Enable XXL-Heading for Carousel

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/porsche-design-system#2621]
Scope
---
Currently, the Carousel only supports the XL-Heading in order to full fill UI definitions the XXL-Heading needs to be available. By definition, content sections are indicated/separated by the XXL-Headings. As Carousel sometimes act as a own section, it is necessary to set the Heading to XXL.

Notes
---
- In the near future: Carousel should not offer a slotted heading or description since it can easily be placed above the Carousel component in form of a pattern. In the meantime, we should move the slotted heading and description above the Carousel prev/next buttons. This way more space is available for a XXL Heading and all teams are getting visually auto migrated to the new placement of the header section.
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/a5845f21-7fe2-46cc-99d5-2f8b537ceb7b)
- Why are we throwing an a11y error when no heading is provided? => should be removed an aria prop shall be introduced instead (don't validate but use a default value for aria-label's region). In addition `h2` should be rendered conditional or maybe even better with pure CSS `h2:empty {display: none;}`
- Maybe we can make skip link reserved "space" conditional (on both sides)

Acceptance criteria
---
- [x] Move heading + description section/slot of Carousel on top of prev/next buttons
- [x] New Pattern (custom heading + description and Carousel) approach is shown and documented on Storefront
- [x] Named `slot="header"` is introduced and placed next to prev/next buttons of Carousel (aligned with `alignHeader`)

Subtasks
---
- [ ] Task

**Comment by leifmarcus** [comment]
Are there any updates on this topic?

**Comment by stephanschroeter** [comment]
It's already possible with:

```
    <p-carousel>
      <p-heading slot="heading" size="xx-large" tag="h3">XXL Heading</p-heading>
      <div>Slide 1</div>
      <div>Slide 2</div>
      <div>Slide 3</div>
    </p-carousel>
```
