### ISSUE TITLE
[BUG] - Tabs bar not working on page translate

### ISSUE THREAD

**Issue by zlatko-stulic** [porsche-design-system/porsche-design-system#2651]
### JS Framework

Angular

### Porsche Design System version

3.2.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

114.0.5735.198

### Reproduction Example

https://designsystem.porsche.com/v3/components/tabs-bar/examples

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/v3/components/tabs-bar/examples
2. Click right-click and then translate the page to a different language.
3. Tabs are not working when clicking after the page is translated. (Only when clicking on a tab next to the font/typography area.
5. See the error in the video below:

https://github.com/porsche-design-system/porsche-design-system/assets/86468671/96306e69-9e1a-40f1-99f3-b9c3d0500bc2

### Expected behavior

Tabs should work even if the page is translated. I've tested this on the design system v2 and everything works ok. This problem is only in the v3 of the design system.

### Notes

- Other components like `Stepper Horizontal` might also be affected. But for now focus on `Tabs Bar` only.
- Time-boxed evaluation for Google Translate test automation setup

**Comment by stephanschroeter** [comment]
Maybe it's also related to custom styles provided by Google, in case it's not blocked.

![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/6746cd64-d197-4926-91af-d3e1b1a25e59)
