### ISSUE TITLE
Allow custom width configuration for dynamic content in flyout

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#2668]
Scope
---
Enhance the Flyout component to allow for a fixed width option, such as 100%, when the content inside the Flyout does not occupy the entire screen or when loading dynamic content. 

[Slack Request](https://porschedev.slack.com/archives/CT7AVHTTQ/p1689333526447259)

Notes  
---
- We could add an option to define the min-width or the width of the flyout by using a CSS Custom Property similar to the `p-flyout-max-width`.
- Inform team "Configure" and "Financial Services", as soon as issue is solved

Acceptance criteria
---
- [ ] The Flyout component width can be set to a fixed width such as 100%.

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
Already implemented.
