### ISSUE TITLE
[BUG] - Breakpoint causes Button-text to not be centered anymore

### ISSUE THREAD

**Issue by RomanSchmidtPDiG** [porsche-design-system/porsche-design-system#2679]
### Contact Details

roman.schmidt@porsche.digital

### JS Framework

Vue 3

### Porsche Design System version

3

### What browsers are you seeing the problem on?

Safari

### Reproduction Example

https://www.porsche.com/germany/models/taycan/taycan-models/taycan-gts/

### Steps to reproduce the behavior

1. Go to Taycan Model Page in Germany
2. Switch to responsive mode and reduce the width < 362px 

### Expected behavior

Due to the padding of the button not being responsive based on the text break point, the text of the button "Neu- und Gebrauchtwagen kaufen" seems to be shifted to the left instead of being centered

<img width="642" alt="Bildschirmfoto 2023-07-19 um 13 40 03" src="https://github.com/porsche-design-system/porsche-design-system/assets/139765530/39fe9ca0-2bf8-4715-bd9d-a4fd56061cbe">
<img width="674" alt="Bildschirmfoto 2023-07-19 um 13 40 27" src="https://github.com/porsche-design-system/porsche-design-system/assets/139765530/3cb1c4a4-3dfe-46e4-b30a-e62c7130a193">
![Screenshot 2023-07-19 at 15 14 45](https://github.com/porsche-design-system/porsche-design-system/assets/139765530/57d604e4-8243-4c41-9079-10e41f5f313b)

**Comment by RomanSchmidtPDiG** [comment]
![Screenshot 2023-07-19 at 15 14 45](https://github.com/porsche-design-system/porsche-design-system/assets/139765530/4f16c57c-8eea-4a69-9875-f47b4079b4ad)

**Comment by o-hook** [comment]
Imho it has nothing to do with the `padding` of the button, because it is intended that it doesn't change regarding to breakpoints because the button itself has always the same layout dimensions. It is more kind of an Browser issue, because the browser doesn't recalculate the available space if text gets wrapped to multiline.
