### ISSUE TITLE
[BUG] - Flyout content is accessible

### ISSUE THREAD

**Issue by MarcelKnobelsdorf** [porsche-design-system/porsche-design-system#2699]
### JS Framework

React

### Porsche Design System version

3.5

### Reproduction Example

https://stackblitz.com/edit/react-5lw9gb?file=App.tsx

### Steps to reproduce the behavior

1. go to https://stackblitz.com/edit/react-5lw9gb?file=App.tsx
2. press Tab until you reach the Flyout button.
3. press Tab again
4. now you are inside the accordion content 

We have some checkbox components inside the accordion that are also accessible when the accordion is open.

![image](https://github.com/porsche-design-system/porsche-design-system/assets/114990926/bba68345-32b5-49c3-a3d8-cf0bfff326ae)

### Expected behavior

Open accordions are not accessible 

### Notes
- probably related https://github.com/porsche-design-system/porsche-design-system/issues/2682

**Comment by stephanschroeter** [comment]
Solved by #2799, new Porsche Design System release will follow asap.
