### ISSUE TITLE
[BUG] - Select wrapper missing blue outline

### ISSUE THREAD

**Issue by MarcelKnobelsdorf** [porsche-design-system/porsche-design-system#2702]
### JS Framework

React

### Porsche Design System version

3.5

### Reproduction Example

https://designsystem.porsche.com/latest/components/select-wrapper/examples#basic-example

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/latest/components/select-wrapper/examples#basic-example
2. navigation to the select wrapper component
3. No blue border as with other active elements.

![image](https://github.com/porsche-design-system/porsche-design-system/assets/114990926/566458fd-7787-4a7e-b950-964dd30799f1)

### Expected behavior

The focus status should be the same as for other active elements.

![image](https://github.com/porsche-design-system/porsche-design-system/assets/114990926/3770b077-bba5-4d3e-8c47-c4a9291532e0)

**Comment by marcelbertram** [comment]
@MarcelKnobelsdorf 
As with form fields there is no possibility to separate a focus state between mouse and keyboard navigation, and we have very prominent input fields for example with the login, we decided to have a more decent focus styling. By default forms have a grey outline and a solid black one when focussed. But we will have a look if we can make the difference more clear
