### ISSUE TITLE
Update Twitter Icon

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/porsche-design-system#2714]
Scope
---
Twitter has launched a new logo, therefore we need to replace the current icon with the new logo.

Note
---
- Give permissions for brand guide asset library (MB)

Acceptance criteria
---
- [ ] Twitter icon is replaced in the Porsche Design System
- [x] Twitter icon is replaced in the Figma library
- [x] Twitter icon is replaced on the [Brand Guide](https://brand.porsche.com/)

Sub-Tasks
---
- [x] clean .svg icon is created

![logo-twitter](https://github.com/porsche-design-system/porsche-design-system/assets/42403731/49e67d9f-d8ca-4e21-b372-ba24383c6214)

**Comment by iamkingsleey** [comment]
Hello @neuncreative, is this issue still open? I will love to jump on it.
