### ISSUE TITLE
Create Motion Tokens

### ISSUE THREAD

**Issue by muellernaumann** [porsche-design-system/porsche-design-system#2717]
Scope
---
We aim to offer fundamental Motion Tokens, such as Duration and Easing, with various characteristics. This will help standardize our own components and empower teams with a clear specification.

Out of Scope
---
- Implementing these tokens within our components (https://github.com/porsche-design-system/porsche-design-system/issues/2697).
- Duration Calculator based on Distance and Size.

Notes  
---
- Reference Link: https://porsche-design-system.github.io/ux-prototype/motion/index.html 
- Think of visualizations for curves in storefront docu
- Token name: `Motion`
- Type: `Duration`
-- `$motionDurationShort: 0.25s`
-- `$motionDurationModerate: 0.4s`
-- `$motionDurationLong: 0.6s`
-- `$motionDurationVeryLong: 1.2s`
- Type: `Easing`
-- `$motionEasingBase: cubic-bezier(0.25,0.1,0.25,1);`
-- `$motionEasingIn: cubic-bezier(0,0,0.2,1);`
-- `$motionEasingOut: cubic-bezier(0.4,0,0.5,1);`

Acceptance criteria
---
- [x] Motion Tokens are added as Styles
- [ ] Generic Motion examples (just like [here](https://porsche-design-system.github.io/ux-prototype/motion/index.html)) are shown on the Storefront under section Styles > Motion 

Subtasks
---
- [ ] …

**Comment by Mayaleeeee** [comment]
Is this still available? @muellernaumann 

I would like to contribute to this.
