### ISSUE TITLE
Select options get displayed in the background while being used within a table

### ISSUE THREAD

**Issue by aleksbjk** [porsche-design-system/porsche-design-system#2725]
### Contact Details

extern.aleksander.bujko@porsche.de

### JS Framework

Angular

### Porsche Design System version

3.5.0.

### What browsers are you seeing the problem on?

Mobile Firefox, Chrome

### Reproduction Example

https://stackblitz.com/edit/angular-xnmnsp-fszw7y?file=src%2Fapp%2Fapp.component.html

### Steps to reproduce the behavior

1. Create a table using the Design System Component
2. Put a select field with some options within a table cell
3. Navigate to the latest table row 
4. If you open the select field the options cannot be selected, since they are getting displayed in the background
![image](https://github.com/porsche-design-system/porsche-design-system/assets/60901406/464a79ad-4d3d-419e-bded-e54f97d5823f)

### Expected behavior

It is possible to use a select field within a table, if it's located in the last row. 

### Notes

- https://github.com/tailwindlabs/tailwindcss/discussions/2672
- https://play.tailwindcss.com/jPbHqRyZN5

**Comment by marcelbertram** [comment]
Reference https://github.com/porsche-design-system/porsche-design-system/issues/2572
