### ISSUE TITLE
[BUG] - Multi-Select visual bugs

### ISSUE THREAD

**Issue by tatjana-mariella** [porsche-design-system/porsche-design-system#2777]
**BLOCKED** First, we need to align custom dropdown code technique. We shouldn't focus on `p-select-wrapper` anymore, but check if `p-select` and `p-multi-select` are visually in sync.

### JS Framework

all frameworks

### Porsche Design System version

3.7.0-rc.0

### Reproduction Example

https://stackblitz.com/edit/zhh4xn?file=index.html

### Steps to reproduce the behavior

1. Go to 'https://stackblitz.com/edit/zhh4xn?file=index.html'
2. Open dropdown
4. See error':
![image](https://github.com/porsche-design-system/porsche-design-system/assets/109523972/77d4d25b-373f-43a6-a3e4-67bda1409df4)

<img width="806" alt="Screenshot 2023-11-13 at 15 54 19" src="https://github.com/porsche-design-system/porsche-design-system/assets/30120450/a94d39e1-2d39-4353-972c-4bed917c7c1e">

### Expected behavior

Dropdown should be at the same hight as select-wrapper. 
Input should have a border radius.

**Comment by sai8151** [comment]
i cant find any UI bug.
