### ISSUE TITLE
[BUG] - Pagination - Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by Rouby** [porsche-design-system/porsche-design-system#2813]
### Contact Details

jonathan.burke@codecentric.de

### JS Framework

React

### Porsche Design System version

3.5.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

117

### Reproduction Example

-

### Steps to reproduce the behavior

https://github.com/porsche-design-system/porsche-design-system/blob/94743f52cce076eef7f96cd0557f4f5b06dbf197/packages/components/src/components/pagination/pagination.tsx#L256

This line seems to be called with `this.navigationElement` not properly initialized.

### Expected behavior

Works / or is not called before init. Or even better, `breakpointMaxNumberOfPageLinks` is solved with pure CSS (e.g. Container Queries, or dynamic horizontal sizing like Pin Code,…) to solve the issue and improve SSR.

### Relevant log output

```shell
Error:
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
at anonymousin https://cdn.ui.porsche.com/porsche-design-system/components/porsche-design-system.pagination.18702b6c07ebcc829f48.js
Line 1 : Column 3601

at updateMaxNumberOfPageLinksin https://cdn.ui.porsche.com/porsche-design-system/components/porsche-design-system.pagination.18702b6c07ebcc829f48.js
Line 1 : Column 3668

at anonymousin https://cdn.ui.porsche.com/porsche-design-system/components/porsche-design-system.v3.5.0.c621d92f5bf71e7c0bdd.js
Line 1 : Column 42859

at Map.forEachin
at MediaQueryList.onin https://cdn.ui.porsche.com/porsche-design-system/components/porsche-design-system.v3.5.0.c621d92f5bf71e7c0bdd.js
Line 1 : Column 42846
```

**Comment by stephanschroeter** [comment]
- `maxNumberOfPageLinks` is deprecated and has no effect anymore
- Mobile + Desktop (`maxNumberOfPageLinks`) view is handled with pure CSS
- Have a look at how the pagination of Carousel is solved
