### ISSUE TITLE
[BUG] - Button has margins in Safari

### ISSUE THREAD

**Issue by Mp4ct** [porsche-design-system/porsche-design-system#2827]
### JS Framework

Framework independent

### Porsche Design System version

3.7.0

### What browsers are you seeing the problem on?

Safari, Mobile Safari

### Browser version

15.1

### Reproduction Example

https://stackblitz.com/edit/react-oiykne?file=App.tsx

### Steps to reproduce the behavior

Open the provided StackBlitz example in Safari. The PButton is not aligned with the top of the viewport. Its button element has margin-top/-bottom of 2px which makes it difficult to align PButton with other elements. Now open the example in any other browser. There, the button sits at the top, no margins.

### Expected behavior

The default browser stylesheet is overwritten with margin: 0 to ensure PButton behaves the same in all browsers.

### Notes
- We should also check the margin reset for other PDS button components.
- When adding `margin: 0;` to reset user-agent style for buttons please add a comment why it's needed.

**Comment by stephanschroeter** [comment]
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/87bd7a85-7b81-4fc8-9533-0f13cb5a6f67)
