### ISSUE TITLE
Replace Macan model signature asset

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2837]
Scope
---
We were notified that the current Macan model signature asset is not the correct one for this year's series, so we need to replace the asset.

Notes  
---
- Keep settings / dimensions of current assets to be aligned
- Source Files for Design: 
[Macan_LZV_Schriftzug_Macan.zip](https://github.com/porsche-design-system/porsche-design-system/files/13067973/Macan_LZV_Schriftzug_Macan.zip)
- Optimised Asset: Will be created by Design together with Developer
- Maybe, add readme which explains difference between `./src/raw` and `./src/optimized`

Acceptance criteria
---
- [ ] Macan model signature asset is replaced with the correct one (but existing one is not deleted to re-use later)
- [x] Asset is updated on figma

Subtasks
---
- [ ] Task

**Comment by muellernaumann** [comment]
is this the right signatur? @marcelbertram 
[Macan-0612.pdf](https://github.com/porsche-design-system/porsche-design-system/files/13067935/Macan-0612.pdf)

**Comment by neuncreative** [comment]
Optimized Macan Asset:
![macan_optimized](https://github.com/porsche-design-system/porsche-design-system/assets/42403731/70f2c0cc-e8cf-45c8-8339-97a1232a6087)
