### ISSUE TITLE
**[BUG]** Carousel touch move does not work in RTL mode

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2841]
Scope
---
Describe clearly the scope of the task.

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by o-hook** [comment]
Can't reproduce the bug. Tested with different Browsers and with iPadOS Safari.
