### ISSUE TITLE
Stabilise Component VRT

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2881]
Scope
---
Currently, the Playwright Component VRT Tests are flaky again because Playwright's default threshold for screenshot comparison was set to 0. Either we should re-enable Playwright's default screenshot comparison threshold or ensure screenshot comparison is stable.

Notes
---
- Does it make sense to use and load simply all component chunks and icon assets by default for VRT test (to eliminate lazy request loading):
  - https://designsystem.porsche.com/v3/partials/component-chunk-links
  - https://designsystem.porsche.com/v3/partials/icon-links
- Try to eliminate resize issues
- Try to not manipulate "on the fly", e.g. change theme within `setupScenario(…)`
- Would it be possible to get a more performant runner? => ask GH business support via PM

Acceptance criteria
---
- [ ] Playwright Component VRT Tests are running stable and reliable

Subtasks
---
- [ ] Task

**Comment by henrijoss** [comment]
Github Runner Resources seem to play a major role in the flakyness of the Tests. 
To log resource usage in docker we can use following command:
`docker run -t --entrypoint /bin/bash ghcr.io/porsche-design-system/porsche-design-system/playwright:v1.39.0-focal-test2 -c "top -n 1"`
To log resource usage in node:
const os = require("node:os");
console.log('Amount of CPUs', os.cpus().length);
console.log('Total Memory in MB', os.totalmem() / 1024 / 1024);
console.log('Free Memory in MB', os.freemem() / 1024 / 1024);

**Comment by henrijoss** [comment]
The cost of a larger github runner in order to resolve this problem seems to be unfeasible since it would be way to expensive:
Pipeline run for Build and Test Workflow: 203 minutes 20 seconds
Cost for cheapest github runner per minute in USD: $0.008 [Github Pricing](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)

203min * 0.008$ = 1.62$ per run

**Comment by henrijoss** [comment]
Another approach could be to use Playwright sharding to improve the resource usage:
[https://playwright.dev/docs/test-sharding](https://playwright.dev/docs/test-sharding)
