### ISSUE TITLE
Create Patterns for Singapore Shop

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#2884]
Scope
---
Create Patterns for the Singapore Shop in a separate repository, reusing existing PDS Components (Vanilla JS) and Styles (SCSS Styles).

Out of Scope
---
- Not integrated or linked in Storefront yet
- No test automation

Notes  
---
- Figma: https://www.figma.com/file/PnBzISaQv6dIRF6rvN5mEi/The-Singapore-Experience?type=design&node-id=884-25980&mode=design&t=ASIBveLxDkcOWCMD-4
- Use visual placeholder (e.g. Skeleton Style) if something (Component or Style) is not yet available
- Use PDS Styles and Components as much as possible
- [Assets for Pattern](https://github.com/porsche-design-system/porsche-design-system/files/13348902/webp.zip)

Acceptance criteria
---
- [x] Source Code of Pattern for Singapore Shop "Homepage" is available in a separate repository (public)
- [x] Source Code of Pattern for Singapore Shop "Product List" is available in a separate repository (public)
- [x] Source Code of Pattern for Singapore Shop "Product Detail" is available in a separate repository (public)
- [x] Source Code of Pattern for Singapore Shop "Checkout" is available in a separate repository (public)
- [x] Singapore Shop Patterns are built with GitHub Actions and available with GitHub Pages (public)

Subtasks
---
- [x] CI: https://github.com/porsche-design-system/patterns/actions
- [x] Source Code: https://github.com/porsche-design-system/patterns/tree/main/patterns/shop-landing-page
- [x] Deployed Pattern: https://porsche-design-system.github.io/patterns/patterns/shop-landing-page/

**Comment by stephanschroeter** [comment]
Shop Homepage:
This pattern includes Flyout “Menu” and Flyout “Search”.
Preview: https://porsche-design-system.github.io/patterns/patterns/shop-homepage/
Source: https://github.com/porsche-design-system/patterns/tree/main/patterns/shop-homepage
 
Product List:
This pattern includes Flyout “Menu”, Flyout “Search”, Flyout “Filter”, Flyout “Wishlist” and Modal “Size Chart”.
Preview: https://porsche-design-system.github.io/patterns/patterns/shop-product-list/
Source: https://github.com/porsche-design-system/patterns/tree/main/patterns/shop-product-list
 
Product Detail:
This pattern includes Flyout “Add to cart” and Modal “Size Chart”.
Preview: https://porsche-design-system.github.io/patterns/patterns/shop-product-detail/
Source: https://github.com/porsche-design-system/patterns/tree/main/patterns/shop-product-detail

Checkout
Preview: https://porsche-design-system.github.io/patterns/patterns/shop-checkout/
Source: https://github.com/porsche-design-system/patterns/tree/main/patterns/shop-checkout
