### ISSUE TITLE
[BUG] - Pin-code current-input id is not set correctly

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#2891]
### JS Framework

All

### Porsche Design System version

3.8.0

### Reproduction Example

https://designsystem.porsche.com/v3/components/pin-code/examples

### Steps to reproduce the behavior

1. Go to [https://designsystem.porsche.com/v3/components/pin-code/examples](https://designsystem.porsche.com/v3/components/pin-code/examples)
2. Inspect input elements, current-input id is on first input
3. Type in some value
4. `current-input` id is gone

### Expected behavior

`current-input` id is set on relevant input element:
- no value is entered at all: set `current-input` id on first input element
- some value is entered: set `current-input` id on the first input element which does not have a value
- all inputs have some value: set `current-input` id on the last input element

**Comment by tatjana-gartner2** [comment]
Since whitespaces are added to the value to allow not in sequence typing, the value value must be sanitised in this calculation`id={index === this.value.length ? currentInputId : null}`
