### ISSUE TITLE
SPIKE: Unique ID's for Form Fields

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#2894]
Scope
---
When visiting the PIN Code examples on the [Storefront](https://designsystem.porsche.com/v3/components/pin-code/examples) and open Chrome Developer Console, Chrome complains about non-unique ID's used for form elements. Therefor, we need to evaluate weather this is a critical issue and how to fix it.

Notes  
---
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/30120450/bab443a2-fe88-4317-b3ae-5b43dafad351)
- In case simply "fixes" are possible, update Storefront examples accordingly
- Related issue: [#2891](https://github.com/porsche-design-system/porsche-design-system/issues/2891)

Acceptance criteria
---
- [x] Risks and solutions rearding Google Chrome's warning about non unique ID's used for form elements are evaluated.

Subtasks
---
- [ ] Task

Findings
- If a form field is submitted, browsers store the value along with the value of the `name` attribute. Some browsers also look at the `id` attribute when storing and filling in data. Using the correct values for the `autocomplete` attribute ensures that the browser fills in the correct values for a form.
- Issue in chrome is only thrown if at least one multi-select/pin-code is used within form on same page (does not matter if second is used within form or without form)
- ❌ Consumers will see the warning in chrome if e.g. multiple multi-selects are used within the same form / different forms on same page https://stackblitz.com/edit/lpg328-wm7263?file=index.html
- ✅  The scenario warned about can not be reproduced for our afffected webcomponents (pin code, multi select)

Reproduction example:
- ❌ The scenario warned about can be reproduced within dummy webcomponents and IDs in shadow dom:  [Stackblitz](https://stackblitz.com/edit/web-platform-76ywuy?file=non-unique-ids.html,unique-ids.html,non-unique-label-id-name-autocomplete.html,non-unique-label-id-name.html,non-unique-label-id-autocomplete.html,non-unique-label-id.html,non-unique-id.html,unique-id.html,unique-label-id-autocomplete.html,unique-label-id-name-autocomplete.html,unique-label-id-name.html,unique-label-id.html,index.html,my-elements.js)

Risks:
Currently the Components Pin Code and Multi Select with non unique IDs are not affected.
Future components without wrapper Text-field, checkbox, radio-button, select can be affected

**Comment by henrijoss** [comment]
Related StackOverflow discussions (suggesting we can ignore this error):
[https://stackoverflow.com/questions/56023322/are-duplicate-ids-allowed-in-separate-shadow-roots](https://stackoverflow.com/questions/56023322/are-duplicate-ids-allowed-in-separate-shadow-roots)
[https://stackoverflow.com/questions/72258610/is-it-semantically-correct-to-have-multiple-inner-elements-with-the-same-id-in?noredirect=1&lq=1](https://stackoverflow.com/questions/72258610/is-it-semantically-correct-to-have-multiple-inner-elements-with-the-same-id-in?noredirect=1&lq=1)
