### ISSUE TITLE
[BUG] - `p-modal` / (`p-flyout`?) has missing box-shadow on sticky footer when rendered later

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#2916]
### Contact Details
https://porschedev.slack.com/archives/CT7AVHTTQ/p1701449059474459

### Porsche Design System version

latest

### Reproduction Example

https://stackblitz.com/edit/react-vvvjic?file=App.tsx

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/react-vvvjic?file=App.tsx
2. Open example in new tab
3. Click on 'Open Modal'
4. Wait for loading to be finished
5. See missing box-shadow on sticky footer
<img width="377" alt="Bildschirmfoto 2023-12-04 um 14 57 28" src="https://github.com/porsche-design-system/porsche-design-system/assets/4380295/9c392529-4056-4a3e-9aa2-9a72ca31b740">

### Expected behavior

Sticky footer (and also header) box-shadow is correctly shown initially and with later rendered content.  
Probably using `IntersectionObserver` (check git history) is the way to go, since `scroll` event handler is unreliable and not needed anymore since `transform: scale` on open/close was removed with the integration of motion tokens.

### Notes
- Check if issue also appears for Flyout and if it's solvable with  `IntersectionObserver` too.
- We should choose one solution (if possible) which works for both, Modal and Flyout
- Maybe connected to #2955 
- Check if CSS Only Solution would be suitable

**Comment by michaelworm** [comment]
Error is still present in 3.14.0: https://stackblitz.com/edit/react-vvvjic-eqn11t?file=App.tsx
