### ISSUE TITLE
[BUG] - Advanced scrolllock causes jumping background in flyout/modal

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#2996]
### Contact Details

[https://porschedev.slack.com/archives/CT7AVHTTQ/p1705410852071209](https://porschedev.slack.com/archives/CT7AVHTTQ/p1705410852071209)

### JS Framework

All

### Porsche Design System version

`>= 3.8.0`

### Reproduction Example

https://www.porsche.com/germany/models/taycan/taycan-models/

### Steps to reproduce the behavior

1. Open iOS Simulator
2. Go to [https://www.porsche.com/germany/models/taycan/taycan-models/](https://www.porsche.com/germany/models/taycan/taycan-models/)
3. Click on “Model Wechseln”
4. See background jumping when opening

### Notes

- This happens because we set the body to `position: fixed` in the advanced scrolllock for IOS
- Setting a `max-width: 100%`, `inset: 0` or `inline-size: 100%` (used by home & nav) on the body when the scrolllock is active would probably fix this issue.

### Expected behavior

No background jumping when opening the flyout or modal

**Comment by stephanschroeter** [comment]
not relevant anymore, since scroll lock has been reverted to simple `overflow: hidden` solution.
