### ISSUE TITLE
[BUG] - Safari doesn't reflect Radio Button Wrapper state visually

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#3012]
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1706528979557009

### JS Framework

all

### Porsche Design System version

3.10.0

### What browsers are you seeing the problem on?

Safari

### Browser version

16.4.

### Reproduction Example

https://stackblitz.com/edit/angular-rmwhsm-2ay7sg?file=src%2Fapp%2Fwithout-prefix%2Ftest-widget.component.ts,src%2Fapp%2Fapp.module.ts

Adjusted example with native inputs (which seams to work as expected)
https://stackblitz.com/edit/angular-rmwhsm-fb8cev?file=src%2Fapp%2Fwithout-prefix%2Ftest-widget.component.ts

### Steps to reproduce the behavior

1. Open Safari
2. Go to https://stackblitz.com/edit/angular-rmwhsm-fb8cev?file=src%2Fapp%2Fwithout-prefix%2Ftest-widget.component.ts
3. Click on unselected Radio Button / Checkbox
4. See error, Radio Button / Checbkox is not visualised as selected

### Expected behaviour

- Radio Button / Checkbox should always reflect the current state visually in Safari

### Notes
- Might be caused because of css `transition` definitions
- Might only be the case when Radio Button or Checkbox is used within a shadowed component (like in the example)
- Similar case (shadowed component which uses Select Wrapper) is already tested by e2e for Select Wrapper
- `packages/components/src/components/icon/icon-styles.ts` => `forceRerenderAnimationStyle` might be helpful?
- `packages/components/src/utils/checkbox-radio-button-wrapper-utils.ts` (if possible it would be good to get rid of the JS workaround)

**Comment by kroofy** [comment]
Additional reproduction example in React here: https://stackblitz.com/edit/react-abgs3p?file=App.tsx
