### ISSUE TITLE
[Feature Request] Center slides in Carousel when less slides than `slidesPerPage`

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#3041]
Scope
---
If Carousel has less slides to visualise than the actual viewport space would offer then these slides are always left/start aligned. This might be visual distracting, therefore we want to align the slides in such a case depending on the the prop `alignHeader`, either center or to the start. In addition, the named slot "controls" shall also be centered in case `alignHeader` is set to `center`.

Notes  
---
- Community Thread: https://porschedev.slack.com/archives/CT7AVHTTQ/p1708010347110459
Slides can be centered with some additional CSS:
[https://splidejs.com/guides/overflow/#centering-slides](https://splidejs.com/guides/overflow/#centering-slides)
In case CSS class reference is not enough: https://splidejs.com/guides/overflow/#by-script

```
    splide: {
      '&:not( .is-overflow ) .splide__list': {
        justifyContent: 'center',
      },
    }
```
- We should also hide the navigation arrows (prev/next) and pagination if there are too less slides which can be shown at once.
- Should we introduce a more generic prop `align` instead of `alignHeader` (downside might be that, `align` is already a default attribute with characteristics)?
- When named slot "controls" becomes centered, we optionally need to reserve space symmetrically for skip link on both sides.
- Changes regarding alignment are only relevant when `alignHeader` is set to `center`

Acceptance criteria
---
- [ ] Carousel slides are centered when `alignHeader` is set to `center` and less slides than `slidesPerPage` are shown.
- [ ] Named slot "controls" of Carousel is centered when `alignHeader` is set to `center` and less slides than `slidesPerPage` are shown.
- [ ] Prev/Next Buttons and Pagination is not rendered when less slides than `slidesPerPage` are shown.
- ~~[ ] Skip Link is not rendered when less slides than `slidesPerPage` are shown.~~
- `skipLinkTarget` prop must be controlled by the user and should follow recommendation as described in the docs:
If more then 5 slides are rendered, the `skipLinkTarget` prop should be set, regardless of the `slidesPerPage` prop.

**Comment by neuncreative** [comment]
Design checked the request, centering slot is approved, centering slides makes sense as well, conditional hiding of the navigation elements when too few items for carousel case.

**Comment by o-hook** [comment]
`skip-link-target` prop must be controlled by the user and should follow recommendation as described in the docs:
If more then 5 slides are rendered, the `skip-link-target` prop should be set, regardless of the `slides-per-page` prop.
