### ISSUE TITLE
Add sample integration for Jest in Angular

### ISSUE THREAD

**Issue by azavodnikov-rxt** [porsche-design-system/porsche-design-system#3066]
Hello Team

as Karma was deprecated in Angular last year, we want to switch to Jest.

Do you mind to add an example how to integrate PDS in Jest on Angular?

Thanks

**Comment by denyo** [comment]
Hello @azavodnikov-rxt, I think what you are looking for is documented here: https://designsystem.porsche.com/v3/developing/angular/testing#testing-with-jest
Or is this incomplete or not working?

**Comment by azavodnikov-rxt** [comment]
You're right... didn't know it

Will try it out thanks.
