### ISSUE TITLE
Show opening/closing transition for Modal and Flyout. when rendered conditionally

### ISSUE THREAD

**Issue by denyo** [porsche-design-system/porsche-design-system#3077]
Scope
---
Currently our `p-modal` and `p-flyout` and potentially other components with a opening/closing transition loose their transitions when rendered conditionally, e.g. added to or removed from the DOM without a timeout or leaving the unopened/closed element lying around.

One example can be seen here, when clicking the `i` buttons under "Sonderaustattungen:
<img width="1137" alt="Bildschirmfoto 2024-03-04 um 15 29 11" src="https://github.com/porsche-design-system/porsche-design-system/assets/4380295/d9fcab49-06c8-4a19-b4a4-2dfdbe1851d1">

https://finder.porsche.com/de/de-DE/details/porsche-cayenne-s-gebraucht-RW3WRZ?condition=used&model=cayenne

Out of Scope
---
List topics that are not part of this task.

Notes  
---
Share any further information that is relevant for processing.

Acceptance criteria
---
- [ ] Criteria

Subtasks
---
- [ ] Task

**Comment by stephanschroeter** [comment]
With the Porsche Design System >= `v3.16.0-rc.0` it's possible to work with a Singleton pattern for Flyout and Modal, both components are able to dynamically re-render in case slot changes occur caused by dynamic rendering etc. Transitions/Animations should work that way as expected.
