### ISSUE TITLE
[FEATURE] Add optgroups to multi select & select

### ISSUE THREAD

**Issue by tkresic** [porsche-design-system/porsche-design-system#3080]
Scope
---
Multi Select and Select component should support optgroups as does regular Select Wrapper: https://designsystem.porsche.com/v3/components/select-wrapper/examples#with-optgroups

Notes  
---
Interface proposal:
```
<p-{multi-}select name="name" label="Some Label" description="Some description" required>
  <p-{multi-}select-optgroup label="Some optgroup label 1">
    <p-{multi-}select-option value="a">Option A</p-multi-select-option>
    <p-{multi-}select-option value="b">Option B</p-multi-select-option>
    <p-{multi-}select-option value="c">Option C</p-multi-select-option>
  </p-{multi-}select-optgroup>
  <p-{multi-}select-optgroup label="Some optgroup label 2">
    <p-{multi-}select-option value="d">Option D</p-multi-select-option>
    <p-{multi-}select-option value="e">Option E</p-multi-select-option>
    <p-{multi-}select-option value="f">Option F</p-multi-select-option>
  </p-{multi-}select-optgroup>
</p-{multi-}select>
```

Also checkout possible Select improvements: https://github.com/porsche-design-system/porsche-design-system/issues/3054

Acceptance criteria
---
- [ ] [Multi Select](https://designsystem.porsche.com/v3/components/multi-select/examples) options can be grouped with optgroups
- [ ] [Select](https://designsystem.porsche.com/v3/components/select/examples) options can be grouped with optgroups

Subtasks
---
- [ ] Task

**Comment by denyo** [comment]
<img width="818" alt="Bildschirmfoto 2024-06-13 um 09 42 53" src="https://github.com/porsche-design-system/porsche-design-system/assets/4380295/6a1373f8-ed14-4cbc-9356-eff1950f83da">
