### ISSUE TITLE
FollowUp: Enhance Playwright E2E tests

### ISSUE THREAD

**Issue by michaelworm** [porsche-design-system/porsche-design-system#3086]
Scope
---
In #3071 we had some leftovers which we want to address after the migration.

Acceptance criteria
---
- [x] (Accessibility) Snapshots are migrated from puppeteer to playwright
- [ ] Investigate tests that are skipped in Safari or Firefox due to flakyness
  - [x] Split and run different browsers in parallel
- [ ] Replace deprecations like `waitForNavigation`, `ElementHandle`
- [ ] Extend TSConfig
  - [https://www.typescriptlang.org/tsconfig#noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny)
  - [https://www.typescriptlang.org/tsconfig#noImplicitReturns](https://www.typescriptlang.org/tsconfig#noImplicitReturns)
- [ ] Use `Locator` all ofer instead of deprecated ElementHandle `$`  [Docs](https://playwright.dev/docs/locators)

**Comment by stephanschroeter** [comment]
<img width="1199" alt="Screenshot 2024-03-06 at 13 51 10" src="https://github.com/porsche-design-system/porsche-design-system/assets/30120450/f08b3c82-5de0-4d2a-8cc3-5d55c0a93671">
