### ISSUE TITLE
[BUG] - Dynamic change of type in Textfield Wrapper

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#3087]
Follow up to [#3023](https://github.com/porsche-design-system/porsche-design-system/issues/3023)

When changing the `type` of the slotted input in the `p-text-field-wrapper` dynamically the changes are not reflected.

### Reproduction Example

[https://stackblitz.com/edit/vhbsu5?file=index.html](https://stackblitz.com/edit/vhbsu5?file=index.html)

1. Go to [https://stackblitz.com/edit/vhbsu5?file=index.html](https://stackblitz.com/edit/vhbsu5?file=index.html)
2. Click button to change type to password
3. See missing password toggle button

### Notes

- Do we want to fix this issue in the `p-text-field-wrapper` or should we only consider this scenario in a new custom `p-text-field` component?

**Comment by stephanschroeter** [comment]
Won't fix, since the scenario shouldn't be very common and I'd prefer to provide a new encapsulated `p-text-field` where the issue shouldn't occur anymore.
