### ISSUE TITLE
Fix flaky Popover pipeline VRT tests

### ISSUE THREAD

**Issue by michaelworm** [porsche-design-system/porsche-design-system#3088]
Scope
---
Some tests are flaky in the pipeline, multiple retries are often needed to get it succeed. This is drastically increasing the time a PR can be merged.

Notes
---
For popover it seems that the position is not reliable in the VRT test

<img width="100%" alt="Bildschirmfoto 2024-03-06 um 12 07 26" src="https://github.com/porsche-design-system/porsche-design-system/assets/3817545/d34f8508-07dd-4a11-bb4c-cb4ac920b092">

![popover-1760-actual](https://github.com/porsche-design-system/porsche-design-system/assets/3817545/d8a4d0e6-f690-4f8e-8b89-c41ba8069be7)
![popover-1760-diff](https://github.com/porsche-design-system/porsche-design-system/assets/3817545/29ba1d25-5372-438e-8f7c-59d246a32744)
![popover-1760-expected](https://github.com/porsche-design-system/porsche-design-system/assets/3817545/707ef095-3d6f-48ab-b6f1-3910aebb557b)

For modal it seems scroll position is not reliable

![Image](https://github.com/porsche-design-system/porsche-design-system/assets/3817545/b10c1572-db5b-4944-839e-eb8ca03e8d00)

Acceptance criteria
---
- [x] ~~Find a way to make Popover VRT test more stable~~ not flaky anymore
- [x] Find a way to make modal scrollposition test more stable (NOTE: Maybe this test is already stable in the meantime since it was refactored already) => #3141

**Comment by michaelworm** [comment]
The VRT test for the Popover component is currently deactivated since it was too flaky and delayed deployments heavily on a regular basis.

**Comment by henrijoss** [comment]
Fixed Problems with E2E Modal Tests (Changed to web first assertion)
https://playwright.dev/docs/best-practices#use-web-first-assertions
