### ISSUE TITLE
[FEATURE] Provide model signatures as inline and block element

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/porsche-design-system#3126]
Scope
---
We need to adjust the component to give the teams more flexibility on how to use the model signature component. Users want to be able to decide whether they want to use the embedded whitespace in each signature or not. Note: white space was implemented to provide a visual balance among all signatures when setting the same height.

Solution proposal: 
`inline` version (padding-top/bottom added + to be not bearing to current implementation) 
`block` version (real target box around the vector) - no safe zone around SVG
**TBD.: Naming is not quite accurate yet, maybe we find something better**
Maybe we also don't need this option at all for the component?

Padding:

**718** 
`padding-top: 2px; padding-bottom: 11px;`
**cayman** 
`padding-top: 3px; padding-bottom: 3px;`
**cayenne** 
`padding-top: 4px; padding-bottom: 3px;`
**taycan** 
`padding-top: 0px; padding-bottom: 1px;`
**turbo s**
`padding-top: 3px; padding-bottom: 11px;`
**turbo**
`padding-top: 3px; padding-bottom: 11px;`
**boxster**
`padding-top: 4px; padding-bottom: 11px;`
**panamera**
`padding-top: 2px; padding-bottom: 11px;`
**911**
`padding-top: 3px; padding-bottom: 11px;`
**macan**
`padding-top: 1px; padding-bottom: 11px;`

Out of Scope
---
- Changing or adding additional components
- New color options, see #3127 

Notes  
---
- Community Thread: https://porschedev.slack.com/archives/CT7AVHTTQ/p1708350598107809
- Prop Name: `safe-zone`, `equalize`, `visually-align`, `vertical-align`

Acceptance criteria
---
- [ ] Model Signature supports behaviour with and without SVG safe-zone
- [ ] New Model Signature behaviour is reflected in figma component
- [ ] New Model Signature behaviour is documented on Storefront

Subtasks
---
- [ ] Task

[singatures_no-safezone.zip](https://github.com/porsche-design-system/porsche-design-system/files/14743669/singatures_no-safezone.zip)

**Comment by stephanschroeter** [comment]
- Shall we use a CSS variable instead of CSS inheritance to overwrite e.g. color? Or event width/height?
