### ISSUE TITLE
[BUG] - False warning when using Nextjs next/head to inject partials

### ISSUE THREAD

**Issue by armingjazi** [porsche-design-system/porsche-design-system#3137]
### Contact Details

a.ghajarjazi@reply.de

### JS Framework

NextJs 14.1.3

### Porsche Design System version

3.13.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

122.0.6261.129

### Reproduction Example

https://stackblitz.com/edit/stackblitz-starters-gbkzym?file=app%2Flayout.tsx

### Steps to reproduce the behavior

1. Load Stackblitz project
2. Inspect page and see console warnings.

### Expected behavior

No warnings should be shown. 

Since NextJs >13 is moving towards an app router architecture, putting partials in the document is not recommended anymore. 

Please provide instructions for integration. Thank you. 

- Make sure to update the Storefront docs, https://designsystem.porsche.com/v3/developing/next-js/getting-started
- Make use of Vercel business support

**Comment by henrijoss** [comment]
### `getMetaTagsAndIconLinks()`

Provide as object to use in either `generateMetadata()` or `export const metadata` and `export const viewport`

- msapplication no longer needed?
- `statusBarStyle: 'white'` does not exist?

```
    themeColor: [
      { media: '(prefers-color-scheme: light)', color: '#FFF' },
      { media: '(prefers-color-scheme: dark)', color: '#0E1418' },
    ],
    appleWebApp: {
      title: 'TITLE_OF_YOUR_APP',
      statusBarStyle: 'white',    
    },
    icons: {
      icon: [
        { url: 'https://cdn.ui.porsche.com/porsche-design-system/meta-icons/favicon.ed9a926c291db9c71baddf935b8d3b04.ico', sizes: "any" },
        { url: 'https://cdn.ui.porsche.com/porsche-design-system/meta-icons/favicon-32x32.d42ac2876697ec701e95e4a4d608fb0e.png', sizes: '32x32', type: 'image/png' },
      ],
      apple: 'https://cdn.ui.porsche.com/porsche-design-system/meta-icons/apple-touch-icon-180x180.bdf11ccd797ba5199164090057919053.png',
    },
    manifest: 'https://cdn.ui.porsche.com/porsche-design-system/meta-icons/manifest.2bdf26ea31a4da66c7559db772445d32.webmanifest',
  }
```

### `getInitialStyles()`

**Comment by henrijoss** [comment]
## Proposed interface for next.js

### Variant 1

Root layout file `layout.tsx`:
´´´
import '@porsche-design-system/components-react/styles/initialStyles';
import '@porsche-design-system/components-react/styles/fontFaces';

export const metadata = {
  ...getMetaTagsAndIconLinks({ format: "object" });
}

export default function RootLayout() {
  getFontLinks({ format: 'object' }).forEach(({ href, ...opts }) => ReactDOM.preload(href, opts));
  getComponentChunkLinks({ components: ['tabs-bar', 'scroller', 'icon'], format: 'object' }).forEach(
    ({ href, ...opts }) => ReactDOM.preload(href, opts)
  );
  getIconLinks({ format: 'object' }).forEach(({ href, ...opts }) => ReactDOM.preload(href, opts));

...
```
