### ISSUE TITLE
[BUG] - pin code is entered twice in iOS

### ISSUE THREAD

**Issue by patrick-kiesel-tree-it** [porsche-design-system/porsche-design-system#3155]
### Contact Details

patrick.kiesel@tree-it.de

### JS Framework

angular

### Porsche Design System version

latest

### What browsers are you seeing the problem on?

Mobile Firefox, Mobile Chrome, Mobile Safari

### Browser version

latest

### Reproduction Example

https://angular-tje8d2.stackblitz.io

### Steps to reproduce the behavior

just start typing the pin code on iOS. The next input field is everytime prefilled with the value of the previous one

### Expected behavior

The next input field not prefilled.

**Comment by henrijoss** [comment]
This issue only occurs when setting the Language to Chinese.
Change language iOS: `General -> Language & Region -> Chinese (Traditional)`

The onInput event can't be cancelled with `e.preventDefault` and the default input behavior is always happening. This may be related to the IME Keyboard mode and to the `compositionend` Event but i wasn't able to log these events.
https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event
