### ISSUE TITLE
[BUG] - pin code is entered in one field for Android

### ISSUE THREAD

**Issue by patrick-kiesel-tree-it** [porsche-design-system/porsche-design-system#3156]
### Contact Details

patrick.kiesel@tree-it.de

### JS Framework

angular

### Porsche Design System version

latest

### What browsers are you seeing the problem on?

Mobile Firefox, Mobile Chrome

### Browser version

latest

### Reproduction Example

https://angular-tje8d2.stackblitz.io

### Steps to reproduce the behavior

just start typing your pin code. All numbers will be in the first input. No focus switch after input a value

### Expected behavior

the focus should switch to the next input after typing one number of the pin code

### Related issues

- https://github.com/orgs/porsche-design-system/projects/14/views/1?pane=issue&itemId=57971727

**Comment by henrijoss** [comment]
Reproduce on macOS:
1. Download & Install [Android Studio](https://developer.android.com/studio) 
2. Go to Device Manager (Toolbar on the right) and add Device which includes Play Store (indicated by PlayStore Icon) e.g. `Pixel 8 Pro API VanillaIceCream`
3. Start Device
4. Visit https://play.google.com/store/apps/details?id=com.tencent.wetype and click Download/Install
5. Log into Google Account
6. After Installation is finished open app and click green buttons until keyboard setup is done
7. Goto https://designsystem.porsche.com/latest/components/pin-code/examples
8. New keyboard should show up when clicking on an input

**Comment by henrijoss** [comment]
|                     | Chrome (macOS)                                                                        | Android IME keyboard                                                                        | Android default keyboard                                                                   | iOS IME keyboard                                                                            | IOS default keyboard                                                                  |
|---------------------|---------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------|
| keydown             | ✅                                                                                     | ✅                                                                                           | ✅                                                                                          | ✅                                                                                           | ✅                                                                                     |
| keydown key         | '1'                                                                                   | 'Unidentified'                                                                              | '1'                                                                                        | '1'                                                                                         | '1'                                                                                   |
| keydown code        | 'Digit1'                                                                              | ''                                                                                          | ''                                                                                         | 'Digit1'                                                                                    | 'Digit1'                                                                              |
| keydown keyCode     | 49                                                                                    | 229                                                                                         | 49                                                                                         | 229                                                                                         | 49                                                                                    |
| keydown prevent     | ✅ (No number is typed when only this event is prevented)                              | ❌ (Number still typed when only this is prevented, Other keys like backspace are prevented) | ✅ (No number is typed when only this event is prevented) No beforeinput/input events fired | ❌ (Number still typed when only this is prevented, Other keys like backspace are prevented) | ✅ (No number is typed when only this event is prevented)                              |
| beforeinput         | ✅                                                                                     | ✅                                                                                           | ✅                                                                                          | ✅                                                                                           | ✅                                                                                     |
| beforeinput data    | '1'                                                                                   | '1'                                                                                         | '1'                                                                                        | '1'                                                                                         | '1'                                                                                   |
| beforeinput prevent | ✅ (No number is typed when only this event is prevented) No input event fired anymore | ✅ (No number is typed when only this event is prevented) No input event fired anymore       | ✅ (No number is typed when only this event is prevented) No input event fired anymore      | ✅ (No number is typed when only this event is prevented) No input event fired anymore       | ✅ (No number is typed when only this event is prevented) No input event fired anymore |
| input               | ✅                                                                                     | ✅                                                                                           | ✅                                                                                          | ✅                                                                                           | ✅                                                                                     |
| input data          | '1'                                                                                   | '1'                                                                                         | '1'                                                                                        | '1'                                                                                         | '1'                                                                                   |
| input prevent       | ❌ (Number and other keys still typed when only this is prevented)                     | ❌ (Number and other keys still typed when only this is prevented)                           | ✅ (No number is typed and only keydown event logged)                                       | ❌ (Number and other keys still typed when only this is prevented)                           | ❌ (Number and other keys still typed when only this is prevented)                     |
