### ISSUE TITLE
[BUG] - Rendering on Next.js Edge runtime crashes on Partials

### ISSUE THREAD

**Issue by switchnollie** [porsche-design-system/porsche-design-system#3169]
### Contact Details

tim.weise@porsche.digital

### JS Framework

Next.js 14.4

### Porsche Design System version

latest

### Reproduction Example

https://stackblitz.com/edit/pds-next-edge-bug?file=app%2Flayout.tsx

### Steps to reproduce the behavior

Just open the example, you'll see the error. Happens for pages with `export const runtime = "edge"` and only if you import anything from `"@porsche-design-system/components-react/partials"`.

### Expected behavior

Edge runtime supported, no unsupported APIs used (supported APIs described [here](https://nextjs.org/docs/app/api-reference/edge)).

### Relevant log output

```shell
X ./node_modules/@porsche-design-system/components-js/partials/index.js:3:13
Module not found: Can't resolve 'crypto'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@porsche-design-system/components-react/partials/index.js
./app/layout.tsx
./node_modules/next/dist/build/webpack/loaders/next-edge-ssr-loader/index.js?absolute500Path=&absoluteAppPath=next%2Fdist%2Fpages%2F_app...
```

**Comment by henrijoss** [comment]
Vercel itself doesn't recommend using the edge runtime anymore.
https://twitter.com/leeerob/status/1780705942734331983
