### ISSUE TITLE
Provide default meta thumbnail image

### ISSUE THREAD

**Issue by marcelbertram** [porsche-design-system/porsche-design-system#3201]
Scope
---
In order to align the default thumbnail images across the different teams according to the new design language we should provide the correct and optimized assets for easily integration in the meta tags.

Notes  
---
- Provide default thumbnail as part of `getMetaTagsAndIconLinks()` partial
- Can the thumbnail then be overwritten, for e.g. product detail pages?
- Evaluate which `width` / `height` is commonly used for `twitter:image` and `og:image`
- Thumbnails need to be provided by design
- Ensure data structure is aligned with Next JS meta data structure when `getMetaTagsAndIconLinks()` is returned as js object
- `og:image` can be tested here:
https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdesignsystem.porsche.com%2Fissue%2F3201%2F
https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdesignsystem.porsche.com%2Fissue%2F3201%2F

Acceptance criteria
---
- [ ] A default thumbnail for `<meta name="twitter:image" />` and `<meta name="og:image" />` is provided by `getMetaTagsAndIconLinks()` partial

Subtasks
---
- [ ] Task

**Comment by marcelbertram** [comment]
See: 
<img width="686" alt="image" src="https://github.com/porsche-design-system/porsche-design-system/assets/42934679/829db1f5-5511-4e3a-8b2f-9fe88c3814a6">

**Comment by stephanschroeter** [comment]
```
<meta
  name="twitter:image"
  content={openGraph.imageUrl ?? fallBackImageUrl}
/>
```
+ Image Open Graph

**Comment by henrijoss** [comment]
![Image](https://github.com/porsche-design-system/porsche-design-system/assets/44018513/afa7db26-e110-4a89-ab41-caf0c5a288be)
