### ISSUE TITLE
[BUG] - Page behind banner (modal) is navigatable

### ISSUE THREAD

**Issue by ninaboese22** [porsche-design-system/porsche-design-system#3310]
### Contact Details

consentmanagement@udg.de

### JS Framework

VanillaJS

### Porsche Design System version

3.15.0

### On which device(s) you can see the bug?

e.g. Windows Desktop 

### In which browsers you can see the bug?

Firefox, Mobile Firefox, Chrome, Mobile Chrome

### Reproduction Example

https://www.porsche.com/germany/

### Steps to reproduce the behavior

1. Go to 'https://www.porsche.com/germany/' use a incognito window
2. Click on 'tab'
3. The focus moves on the page behind the banner.

### Expected behavior

The focus should remain on the banner and move within it.

**Comment by stephanschroeter** [comment]
This won't be possible with `v3.16.0` anymore which will be released soon. With `v3.16.0` we've refactored the Modal component to make use of native `<dialog/>` element which has a built-in focus trap. The Cookie Consent Team would need to update to this version as soon as it's released.

**Comment by stephanschroeter** [comment]
Fixed with `v3.16.0`
