### ISSUE TITLE
[FEATURE] Re-issued: Add option to make footer of Flyout always "fixed" in addition to "sticky"

### ISSUE THREAD

**Issue by neuncreative** [porsche-design-system/porsche-design-system#3422]
The case has been re-issued with UX! UX has agreed that for specific use-cases, a consistent fixed footer in the flyout makes sense:

When a form is split into several steps (wizard) -> consistent positioning of the proceed button in the fixed footer
When the length of content varies due to a filter/search -> no jumping of the button with consistent positioning of the proceed button in the fixed footer.

Scope
---
Currently the Flyout supports a sticky footer slot. We should give the possibility to make it configurable and offer a fixed footer too. 

Notes  
---
- Community Thread: https://porschedev.slack.com/archives/CT7AVHTTQ/p1710410848708119
- When using a fixed footer, a sub-footer might not be possibly anymore or needs to be visualized as part of the fixed footer
- JS solution is not preferred
- Evaluate all possible solutions and discuss them with the team
- Explore how other design systems deal with fixed footer within a Flyout.
- Old Ticket: https://github.com/porsche-design-system/porsche-design-system/issues/3119
- Whole flyout has to be scrollable even when fixed footer is used
- Slot sub footer shall be have the same independent if footer is sticky or fixed
- Tbd. What about sticky/fixed header?
- Tbd. What about fixed footer + sticky sub-footer?
- Tbd. What about having a generic flyout where e.g. `<p-dialog-header position="fixed"/>` can be slotted?
- Tbd. Spike how generic other design systems are in this topic?
- Tbd. Consider changes might also be relevant to Modal
- Tbd. How to deal with box-shadow for e.g. footer area when `footer-position = fixed` is set
- Theoretically, the best solution without side effects would be to provide a `min-height / min 1fr` for the content area

Acceptance criteria
---
- [ ] Flyout supports the footer to be positioned `sticky` or `fixed` by extending the interface with the prop `footer-position = 'sticky' | 'fixed' = 'sticky'`.

Subtasks
---
- [ ] Task

**Comment by henrijoss** [comment]
Resolved with [Flyout, Modal dismiss button fix (issue/3558) #3574](https://github.com/porsche-design-system/porsche-design-system/pull/3574)

**Comment by marcelbertram** [comment]
@felixmagnus with the latest release 3.21.0 we added the option for the footer to be fixed: https://designsystem.porsche.com/v3/components/flyout/examples#footer-behavior

**Comment by felixmagnus** [comment]
Oh, right, I did not see that! Sorry! That's exactly what we were looking for!
