### ISSUE TITLE
[FEATURE] - Inverted Dropdown

### ISSUE THREAD

**Issue by sarahouis** [porsche-design-system/porsche-design-system#3453]
Acceptance Criteria
---
- [ ] CSS Variables available for overriding colors
- [ ] Example documented in stackblitz

### Portfolio

Customer

### ART and Team

Physical Products -  Team Shopfront / CX

### Contact Details

sarah.scherbaum@porsche.digital

### Problem

Initiated by the merge of PLX and shop.porsche.com, the brand PORSCHE DESIGN shall be highlighted with an inverted colouring for the dropdown if one specific item is selected. Only the color of the select button shall change (not the complete menu) in order to comply with the new display of the brand.

### Solution ideas and examples

Overall background and concept : https://www.figma.com/design/BYh7Zcc8MQCN5BF5d7vgNa/Handover?node-id=6920-27354&t=PVUEsrssIS2Obf35-11) 

Our solution:  https://www.figma.com/design/BYh7Zcc8MQCN5BF5d7vgNa/Handover?node-id=7324-167048&t=PVUEsrssIS2Obf35-11)

### Business priority

High

### Available assisting resources

UX Designer (1 day), FE Dev (1 day)

**Comment by marcelbertram** [comment]
![Image](https://github.com/user-attachments/assets/e011d72d-5f71-4f04-8304-c159cd493882)
