### ISSUE TITLE
Provide AG Grid CSS Theme as sub package of PDS

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#3458]
Scope
---
In order to streamline different self-maintained use cases of the AG Grid at Porsche we want to provide a documentation page in the design system and a centralized, versioned CSS AG Grid theme delivered as sub package of the Porsche Design System npm distribution.

Out of Scope
---
- No license management for AG Grid and general AG setup instructions, this is part of the teams responsibility

Notes  
---
- [AG Grid Community](https://www.npmjs.com/package/ag-grid-community) can be used for test automation (if necessary a licensed version is also possible if needed)
- All CSS colors should be defined with a CSS Variables (if possible even with a PDS Theme Light Fallback, e.g. `var(--xyz, #123)`)
- https://www.ag-grid.com/theme-builder/
- Reuse PDS Styles
- Think of providing the related assets as sub-package, e.g. @porsche-design-system/components-{js|angular|react|vue}/ag-grid
- Include test coverage
- Include documentation page
- We should think of integrate the AG Grid StackBlitz example by an StackBlitz iFrame.
- Evaluate if we can re-use PDS Icons for AG Grid (time-boxed)
- If it helps, there's also a Figma AG Grid available: https://www.ag-grid.com/javascript-data-grid/ag-grid-design-system/#customising-the-design-system
- Think of adding a peerDependency range for PDS x AG Grid
- Optional: Try to work with Contribution Workflow and document it (including pain points)

Example Files from teams
---
- [css (1).zip](https://github.com/user-attachments/files/16745796/css.1.zip)
- [aggrid-porsche-theme (1).css.zip](https://github.com/user-attachments/files/16745801/aggrid-porsche-theme.1.css.zip)
- [AG Grid Theme-v60-20240815_143520 (1).pdf](https://github.com/user-attachments/files/16745797/AG.Grid.Theme-v60-20240815_143520.1.pdf)

Acceptance criteria
---
- [ ] PDS CSS Theme/Style for AG Grid is distributed as sub package of `@porsche-design-system/components-{js|angular|react|vue}/ag-grid`
- [ ] A new documentation section **AG Grid** is available at https://designsystem.porsche.com/v3/ag-grid with all relevant information and a working StackBlitz integration example for Vanilla JS, React, Angular and Vue.

Subtasks
---
- [x] Add `ag-theme-pds.css` with correct styles
- [x] Add `ag-grid` subpackage of `components-js`
- [x] Add `ag-grid` subpackage of `components-react`
- [x] Add `ag-grid` subpackage of `components-angular`
- [x] Add `ag-grid` subpackage of `components-vue`
- [x] Add Unit Test
- [x] Add example page `components-js` (VRT)
- [x] Add example page `components-js` (Storefront)
- [x] Add VRT Test
- [x] Add example page `react` (Storefront)
- [x] Add example page `angular` (Storefront)
- [x] Add example page `vue` (Storefront)
- [x] Add documentation page (Only use ag-grid-community package!)
- [x] Add integrated Stackblitz example
- [x] Add peerDependency of `ag-grid`
- [x] Evaluate Icon reuse
- [ ] Check Filter Dropdown
- [ ] Smoke test to check package exists

Questions
---
- Always import from `components-js/ag-grid/*.css` or copy css to each framework package? plain css files can't be reexported
- AG grid enterprise for storefront? Use community features only?
- Header Icon gap too small

**Comment by michaelworm** [comment]
Update `run-prepare-release-components.sh` because of dependency of `utilities/ag-grid` to `@porsche-design-system/components-js`

**Comment by michaelworm** [comment]
- [x]  Add ag-theme-pds.css with correct styles
- [x] Add ag-grid subpackage of components-js
- [x] Add Unit Test
- [x] Add example page components-js (VRT)
- [ ] Add example page components-js (Storefront)
- [ ] Add VRT Test
- [x] Add example page react (Storefront)
- [x] Add example page angular (Storefront)
- [x] Add example page vue (Storefront)
- [ ] Add documentation page (Only use ag-grid-community package!)
- [ ] Add integrated Stackblitz example
- [ ] Adjust Docker release script run-prepare-release-components.sh to also update ag-grid package components-js dependency
- [x] Add peerDependency of ag-grid
- [x] Evaluate Icon reuse
- [x] Add Checkbox Icons
