### ISSUE TITLE
[BUG] - Broken Flyout Animation

### ISSUE THREAD

**Issue by henrijoss** [porsche-design-system/porsche-design-system#3475]
### JS Framework

All

### Porsche Design System version

3.18.0

### On which device(s) you can see the bug?

macOS

### In which browsers you can see the bug?

Chrome

### Browser version

Version 127.0.6533.120

### Reproduction Example

see beyond

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/v3/components/flyout/examples#example-scrollable-footer-with-sticky-footer-and-sub-footer
2. Click `Open Flyout`
3. See Broken Fade-In Animation

### Expected behavior

Fade-In Animation working as correctly

### Notes

- [Slack Thread](https://porschedev.slack.com/archives/CT7AVHTTQ/p1724070009320889)
- Worked in previous Chrome versions

**Comment by henrijoss** [comment]
Issue no longer exists in Chrome Version 128.0.6613.85

**Comment by o-hook** [comment]
Dito, can't reproduce this issue in Chrome  128.0.6613.85
