### ISSUE TITLE
[BUG] - Bug in jsdom-polyfill dependency

### ISSUE THREAD

**Issue by leifmarcus** [porsche-design-system/porsche-design-system#3511]
### Contact Details

markus.wessollek@mhp.com

### JS Framework

JSDom (Vitest)

### Porsche Design System version

3.18.0

### On which device(s) you can see the bug?

Testing environments when using it in JSDom

### Reproduction Example

https://github.com/calebdwilliams/construct-style-sheets/issues/130

### Steps to reproduce the behavior

The Bug is introduced within the [`construct-style-sheets-polyfill`](https://www.npmjs.com/package/construct-style-sheets-polyfill), that [is used](https://github.com/porsche-design-system/porsche-design-system/blob/776f6e76f66025b24eaff4b9654f589765233e8c/packages/components-js/projects/jsdom-polyfill/src/index.js#L2) inside the `jsdom-polyfill`.

I created already [a bug report](https://github.com/calebdwilliams/construct-style-sheets/issues/130) on their github repostiory.

I'm not sure, how to reproduce the bug, the error I get when running the polyfill in vitest, I always get the Error: `Error: Uncaught [ReferenceError: document is not defined]`, which is referring to the If condition where `!document` is used as condition.

### Expected behavior

I just created the Bug Issue, so that you can probably watch the changes in the [`construct-style-sheets-polyfill`](https://www.npmjs.com/package/construct-style-sheets-polyfill) dependency and update it, when the bug is fixed.

### Relevant log output

```shell
-- no outputs --
```

**Comment by henrijoss** [comment]
Should be fixed with `3.19.0` where we added a replacement for the bug in the [construct-style-sheets-polyfill](https://www.npmjs.com/package/construct-style-sheets-polyfill) package.

**Comment by henrijoss** [comment]
Resolved with: https://github.com/porsche-design-system/porsche-design-system/pull/3481
