### ISSUE TITLE
[BUG] - Dismiss Button of Flyout overlaps content area

### ISSUE THREAD

**Issue by stephanschroeter** [porsche-design-system/porsche-design-system#3558]
### Contact Details

https://porschedev.slack.com/archives/CT7AVHTTQ/p1729508646708979

### JS Framework

- any

### Porsche Design System version

- 3.20.0

### On which device(s) you can see the bug?

- MacBook Pro

### In which browsers you can see the bug?

Chrome

### Reproduction Example

- https://stackblitz.com/edit/bgdsen?file=index.html

### Steps to reproduce the behavior

1. Go to https://stackblitz.com/edit/bgdsen?file=index.html
3. Try to click the visible part of the button underneath the dismiss button
4. See error, button is not clickable

### Expected behavior

- Invisible part of dismiss button should not overlap content part

**Comment by henrijoss** [comment]
Resolved with: https://github.com/porsche-design-system/porsche-design-system/pull/3574
